### ISSUE TITLE
Error in running backup from pip3.

### ISSUE THREAD

**Issue by anthonycroberts** [bluppfisk/deepblu-tools#7]
Any thoughts why I might be getting the error below?  Tried on MacOS & two different Linux boxes with the same result.

```
$ deepblu-backup -u "[e-mail addres]" -p "[password]"
Getting published logs
Loading first 100 published logs from Deepblu API...
Found all the published logs!
Traceback (most recent call last):
  File "/home/aroberts/.local/bin/deepblu-backup", line 8, in <module>
    sys.exit(main())
  File "/home/aroberts/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/aroberts/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/aroberts/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aroberts/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/aroberts/.local/lib/python3.9/site-packages/deepblu_tools/bin/cli.py", line 109, in main
    logbook = dm.DeepbluLogBook(posts, deepblu_user, max_posts=max_logs)
  File "/home/aroberts/.local/lib/python3.9/site-packages/deepblu_tools/models/deepblu/log_book.py", line 28, in __init__
    self.owner = deepblu_user.to_person_type()
  File "/home/aroberts/.local/lib/python3.9/site-packages/deepblu_tools/models/deepblu/user.py", line 38, in to_person_type
    sex=getattr(um.SexType, self.gender.upper()),
  File "/usr/lib/python3.9/enum.py", line 405, in __getattr__
    raise AttributeError(name) from None
AttributeError: OTHER
$ 
```

**Comment by bluppfisk** [comment]
thanks for spotting and reporting!
should be fixed in 2.1.3 (new master)
