### ISSUE TITLE
Backup errs if birthday not added to deepblu.

### ISSUE THREAD

**Issue by anthonycroberts** [bluppfisk/deepblu-tools#8]
I closed the other issue after it successfully downloaded (after I added my birthday to deepblu).  (Thanks for responding so quickly!)  I’m not sure if this is a bug or not, but I would note that it erred until I added it to their system.  See below.  

`% deepblu-backup -u "[email]" -p "[password]"
Getting published logs
Loading first 100 published logs from Deepblu API...
Found all the published logs!
Traceback (most recent call last):
  File "/usr/local/bin/deepblu-backup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deepblu_tools/bin/cli.py", line 109, in main
    logbook = dm.DeepbluLogBook(posts, deepblu_user, max_posts=max_logs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deepblu_tools/models/deepblu/log_book.py", line 28, in __init__
    self.owner = deepblu_user.to_person_type()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deepblu_tools/models/deepblu/user.py", line 44, in to_person_type
    birthdate=um.EncapsulatedDateTimeType(self.birthday.isoformat()),
                                          ^^^^^^^^^^^^^
AttributeError: 'DeepbluUser' object has no attribute 'birthday'
%`

**Comment by bluppfisk** [comment]
fixed that too, in 2.1.4. Let me know how you fare :)
